project_id = "dpgxzkwmfgvevbssdkai"

[functions.process-image]
verify_jwt = false

[functions.telegram-bot]
verify_jwt = false

[functions.get-user-data]
verify_jwt = false

[functions.verify-admin]
verify_jwt = false

[functions.telegram-generate]
verify_jwt = false
