import { createContext, useContext, useState, useEffect, ReactNode } from "react";

type Lang = "uz" | "ru";

interface LanguageContextType {
  lang: Lang;
  setLang: (l: Lang) => void;
  t: (key: string) => string;
}

const translations: Record<Lang, Record<string, string>> = {
  uz: {
    // Navbar / Header
    "nav.features": "Imkoniyatlar",
    "nav.howItWorks": "Qanday ishlaydi",
    "nav.pricing": "Narxlar",
    "nav.roadmap": "Rejalar",
    "nav.login": "Kirish",
    "nav.getStarted": "Bepul boshlash",
    "nav.logout": "Chiqish",

    // Dashboard
    "dash.title": "Yangi rasm",
    "dash.subtitle": "Mahsulot rasmlaringizni yarating va boshqaring",
    "dash.createNew": "Yangi rasm yaratish",
    "dash.noImages": "Hali rasmlar yo'q",
    "dash.noImagesDesc": "Birinchi mahsulot rasmingizni yarating",
    "dash.login": "Tizimga kirish",
    "dash.loginDesc": "Email va parolingizni kiriting",
    "dash.loginBtn": "Kirish",
    "dash.loginLoading": "Kirish...",
    "dash.loginError": "Email va parol kiriting",
    "dash.adminLogin": "Admin kirish",
    "dash.adminLoginDesc": "Admin email va parolni kiriting",
    "dash.adminNoAccess": "Admin ruxsati yo'q",
    "dash.sessionError": "Sessiya tekshirib bo'lmadi",
    "dash.error": "Xatolik yuz berdi",
    "dash.processing": "Qayta ishlanmoqda...",
    "dash.processingTime": "Odatda 30-60 soniya davom etadi",
    "dash.seconds": "soniya",
    "dash.step.analyzing": "Rasm tahlil qilinmoqda",
    "dash.step.scene": "Sahna yaratilmoqda",
    "dash.step.lighting": "Yoritish qo'shilmoqda",
    "dash.step.quality": "Tekshirilmoqda",
    "dash.original": "Asl rasm",
    "dash.aiResult": "AI natija",
    "dash.download": "Yuklab olish",
    "dash.newImage": "Yangi rasm",
    "dash.uploadTitle": "Mahsulot rasmini yuklang",
    "dash.uploadDesc": "Istalgan formatda — 10MB gacha",
    "dash.uploadBtn": "Bosing yoki rasmni tashlang",
    "dash.uploadLabel": "Mahsulot surati",
    "dash.modelType": "Model turi",
    "dash.withoutModel": "📦 Modelsiz",
    "dash.withoutModelDesc": "Faqat mahsulot",
    "dash.withModel": "🧑 Modelli",
    "dash.withModelDesc": "Model bilan",
    "dash.sceneType": "Sahna turi",
    "dash.studio": "Studiya",
    "dash.nature": "Tabiat",
    "dash.lifestyle": "Lifestyle",
    "dash.minimalist": "Minimalist",
    "dash.infographic": "Infografika",
    "dash.imageSize": "Rasm o'lchami: 1080 × 1440 px (3:4)",
    "dash.noCredits": "Kredit tugadi",
    "dash.generateBtn": "Rasm yaratish (1 kredit)",
    "dash.history": "Tarix",
    "dash.imageReady": "Rasm tayyor! ✨",
    "dash.onlyImages": "Faqat rasm fayllari qabul qilinadi",
    "dash.tooLarge": "Rasm juda katta (max 10MB)",
    "dash.networkError": "Tarmoq xatosi. Internet aloqangizni tekshiring.",
    "dash.authExpired": "Autentifikatsiya muddati o'tgan. Ilovani qayta oching.",
    "dash.aiBusy": "AI tizimi band. 1-2 daqiqadan keyin qayta urinib ko'ring.",
    "dash.tgAuthNotFound": "Telegram autentifikatsiyasi topilmadi. Ilovani qayta oching.",
    "dash.sessionExpired": "Sessiya tugagan. Qayta kiring.",
    "dash.uploadError": "Rasmni yuklashda xatolik",
    "dash.saveError": "Ma'lumot saqlashda xatolik",
    "dash.aiError": "AI xizmati bilan bog'lanishda xatolik",
    "dash.relogin": "Tizimga qayta kiring va yana urinib ko'ring",
    "dash.noCreditsBalance": "Kredit tugagan. Balansni to'ldiring",
    "dash.unknownError": "Noma'lum xatolik yuz berdi. Qayta urinib ko'ring.",
    "dash.downloading": "Yuklab olinmoqda...",
    "dash.downloaded": "Yuklab olindi!",
    "dash.downloadTelegram": "Rasm brauzerda ochildi. Rasmni bosib turing va saqlang.",
    "dash.downloadNewTab": "Rasm yangi oynada ochildi.",
    "dash.downloadError": "Yuklab olishda xatolik",

    // Generate
    "gen.newImage": "Yangi rasm",
    "gen.back": "Ortga",
    "gen.step.upload": "Yuklash",
    "gen.step.settings": "Sozlash",
    "gen.step.result": "Natija",
    "gen.uploadTitle": "Mahsulot rasmini yuklang",
    "gen.uploadDesc": "JPG, PNG yoki WEBP — 5MB gacha",
    "gen.uploadBtn": "Bosing yoki rasmni tashlang",
    "gen.uploadLabel": "Mahsulot surati",
    "gen.fileTooLarge": "Fayl hajmi 5MB dan kichik bo'lishi kerak",
    "gen.continue": "Davom etish",
    "gen.settingsTitle": "Sozlamalarni tanlang",
    "gen.settingsDesc": "AI tanlangan sozlamalarga qarab rasm yaratadi",
    "gen.modelType": "👤 Model turi",
    "gen.withModel": "Modelli",
    "gen.withModelDesc": "Inson model bilan",
    "gen.withoutModel": "Modelsiz",
    "gen.withoutModelDesc": "Faqat mahsulot",
    "gen.scene": "🎬 Holat / Fon",
    "gen.nature": "Tabiat",
    "gen.natureDesc": "Tabiat fonida",
    "gen.lifestyle": "Lifestyle",
    "gen.lifestyleDesc": "Hayotiy muhit",
    "gen.studio": "Studia",
    "gen.studioDesc": "Studia foni",
    "gen.minimalist": "Minimalist",
    "gen.minimalistDesc": "Oddiy va toza",
    "gen.infographic": "Infografika",
    "gen.infographicDesc": "Ma'lumotli dizayn",
    "gen.yourImage": "Sizning rasmingiz",
    "gen.generate": "AI bilan tayyorlash",
    "gen.sizeInfo": "📐 1080×1440 • ⚡ Tayyor rasm",
    "gen.processing": "AI rasmni tayyorlamoqda...",
    "gen.processingDesc": "Marketplace rasm tayyorlanmoqda. 20-40 soniya kuting.",
    "gen.analyzing": "Mahsulot tahlil qilinmoqda",
    "gen.creatingBg": "foni yaratilmoqda",
    "gen.addingModel": "Model qo'shilmoqda",
    "gen.proComposition": "Kompozitsiya tayyorlanmoqda",
    "gen.resizing": "1080×1440 o'lchamga moslashtirilmoqda",
    "gen.done": "Tayyor! 🎉",
    "gen.download": "Yuklab olish",
    "gen.newImageBtn": "Yangi rasm",
    "gen.original": "Asl rasm",
    "gen.aiResult": "AI natijasi",
    "gen.error": "Xatolik yuz berdi. Qayta urinib ko'ring.",
    "gen.restart": "Qayta boshlash",
    "gen.success": "Rasm muvaffaqiyatli tayyorlandi!",
    "gen.uploadError": "Yuklashda xatolik",
    "gen.downloadError": "Yuklashda xatolik",
    "gen.downloaded": "Rasm yuklandi!",
    "gen.processError": "Rasmni qayta ishlashda xatolik",

    // Balance
    "bal.title": "Balans",
    "bal.dashboard": "Dashboard",
    "bal.currentBalance": "Joriy balans",
    "bal.imagesLeft": "ta rasm qoldi",
    "bal.images": "ta rasm",
    "bal.selectPackage": "Paket tanlang",
    "bal.popular": "Ommabop",
    "bal.sum": "so'm",
    "bal.perImage": "so'm/rasm",
    "bal.transferTo": "Quyidagi karta raqamga o'tkazing:",
    "bal.copyCard": "Bosib nusxa oling",
    "bal.cardCopied": "Karta raqam nusxalandi",
    "bal.card": "Karta",
    "bal.screenshot": "To'lov skrinshoti:",
    "bal.uploadScreenshot": "Skrinshot yuklang",
    "bal.submitPayment": "✅ To'lov qildim",
    "bal.submitting": "Yuborilmoqda...",
    "bal.submitted": "To'lov so'rovi yuborildi! Admin tasdiqlashini kuting.",
    "bal.adminNote": "Admin tasdiqlashidan so'ng kreditlar hisobingizga qo'shiladi",
    "bal.history": "To'lov tarixi",
    "bal.approved": "✅ Tasdiqlandi",
    "bal.rejected": "❌ Rad etildi",
    "bal.pending": "⏳ Kutilmoqda",
    "bal.loginRequired": "Tizimga kiring",
    "bal.error": "Xatolik yuz berdi",

    // Landing - Hero
    "hero.badge": "AI yordamida mahsulot fotosuratlari",
    "hero.title1": "Mahsulot rasmlarini",
    "hero.titleHighlight": "yangi darajaga",
    "hero.title2": "olib chiqing",
    "hero.desc": "Istalgan mahsulot rasmini yuklang — AI fonni olib tashlaydi, yorug'likni sozlaydi va Uzum, Wildberries, Ozon uchun tayyor rasm yaratadi.",
    "hero.cta": "Bepul boshlash — 1 ta rasm",
    "hero.howItWorks": "Qanday ishlaydi?",
    "hero.step1": "Yuklash",
    "hero.step1Desc": "Rasmni yuklang",
    "hero.step2": "Ishlash",
    "hero.step2Desc": "AI sehrini ko'ring",
    "hero.step3": "Yuklab olish",
    "hero.step3Desc": "Tayyor rasmni oling",
    "hero.before": "Oldin",
    "hero.after": "Keyin",
    "hero.showcase1": "Krossovka",
    "hero.showcase2": "Kosmetika",
    "hero.showcase3": "Soat",
    "hero.showcaseDesc": "Haqiqiy AI natijalari — har qanday mahsulot uchun professional fotosurat",

    // Landing - Features
    "feat.label": "Imkoniyatlar",
    "feat.title": "Barcha kerakli vositalar",
    "feat.desc": "Brauzeringizda. Uskunasiz, fotografsiz.",
    "feat.bg.title": "Fonni olib tashlash",
    "feat.bg.desc": "AI mahsulotni aniq kesib oladi — toza qirralar, istalgan fonga tayyor.",
    "feat.light.title": "Yoritish",
    "feat.light.desc": "Yoritish avtomatik qo'llanadi — soyalar, yaltiroqlik va chuqurlik.",
    "feat.detail.title": "Detal aniqligi",
    "feat.detail.desc": "Tekstura va mayda detallarni kuchaytiradi, tabiiy ko'rinishni saqlagan holda.",
    "feat.market.title": "Marketplace optimizatsiya",
    "feat.market.desc": "Uzum, Wildberries, Ozon uchun to'g'ri o'lcham va formatda avtomatik tayyorlash.",
    "feat.style.title": "5 ta stil",
    "feat.style.desc": "Studiya fonidan infografikagacha — kerakli kayfiyatni tanlang.",
    "feat.size.title": "Katta o'lcham",
    "feat.size.desc": "Rasmlarni yuqori resolutsiyada yaratish.",
    "feat.speed.title": "Tez ishlash",
    "feat.speed.desc": "Natijani soniyalarda oling. Butun katalogni batch rejimda ishlating.",

    // Landing - Marketplace
    "market.label": "Marketplace uchun tayyor",
    "market.title1": "Har bir",
    "market.titleHighlight": "marketplace",
    "market.title2": "uchun optimallashtirilgan",
    "market.desc": "Platformani tanlang — biz o'lcham, padding va talablarni avtomatik sozlaymiz.",

    // Landing - Pricing
    "price.label": "Narxlar",
    "price.title": "Sodda va",
    "price.titleHighlight": "arzon narxlar",
    "price.desc": "Bepul boshlang. Kerak bo'lganda kengaytiring.",
    "price.free": "Bepul",
    "price.freeDesc": "Sinab ko'ring",
    "price.freeFeat1": "1 ta bepul rasm",
    "price.freeFeat2": "Barcha stil presetlar",
    "price.start": "Boshlash",
    "price.buy": "Sotib olish",
    "price.popular": "Eng ommabop",
    "price.onetime": "Bir martalik sinov",
    "price.small": "Kichik paket",
    "price.medium": "O'rtacha paket",
    "price.active": "Faol sotuvchilar uchun",
    "price.big": "Katta do'konlar uchun",
    "price.business": "Biznes paket",
    "price.imageGen": "ta rasm generatsiya",
    "price.hd": "HD sifat",
    "price.allFormats": "Barcha formatlar",
    "price.viaTelegram": "Telegram bot orqali",
    "price.batch": "Batch ishlash",
    "price.fastSupport": "Tezkor support",
    "price.personalSupport": "Shaxsiy support",
    "price.saving": "tejamkorlik",
    "price.hint": "💡 Ko'proq sotib olsangiz — har bir rasm arzonroq!",

    // Landing - Roadmap
    "road.label": "Tez kunda",
    "road.title": "Rejalarimiz",
    "road.desc": "Marketplace sotuvchilari uchun eng yaxshi vositalarni yaratmoqdamiz.",
    "road.infographic": "AI Infografika",
    "road.infographicDesc": "Mahsulot ma'lumotlaridan avtomatik infografika yaratish.",
    "road.video": "AI Video",
    "road.videoDesc": "Marketplace listing uchun qisqa mahsulot videolari.",
    "road.model": "Virtual Model",
    "road.modelDesc": "AI yaratgan modellar — fotosessiyasiz.",
    "road.analysis": "Raqobatchi tahlili",
    "road.analysisDesc": "Raqobatchilar rasmlarini tahlil qilib, tavsiyalar olish.",
    "road.lang": "Ko'p tilli interfeys",
    "road.langDesc": "O'zbek, Rus va Ingliz tillarida to'liq qo'llab-quvvatlash.",

    // Landing - CTA
    "cta.title": "Mahsulot rasmlaringizni yangi darajaga olib chiqing",
    "cta.desc": "Minglab marketplace sotuvchilari bilan birga rasmlar yarating.",
    "cta.btn": "Bepul boshlash — 1 ta rasm",

    // Footer
    "footer.features": "Imkoniyatlar",
    "footer.pricing": "Narxlar",
    "footer.login": "Kirish",
  },
  ru: {
    // Navbar / Header
    "nav.features": "Возможности",
    "nav.howItWorks": "Как работает",
    "nav.pricing": "Цены",
    "nav.roadmap": "Планы",
    "nav.login": "Войти",
    "nav.getStarted": "Начать бесплатно",
    "nav.logout": "Выйти",

    // Dashboard
    "dash.title": "Новое изображение",
    "dash.subtitle": "Создавайте и управляйте изображениями товаров",
    "dash.createNew": "Создать новое",
    "dash.noImages": "Пока нет изображений",
    "dash.noImagesDesc": "Создайте первое изображение товара",
    "dash.login": "Вход в систему",
    "dash.loginDesc": "Введите email и пароль",
    "dash.loginBtn": "Войти",
    "dash.loginLoading": "Вход...",
    "dash.loginError": "Введите email и пароль",
    "dash.adminLogin": "Вход для админа",
    "dash.adminLoginDesc": "Введите email и пароль админа",
    "dash.adminNoAccess": "Нет прав администратора",
    "dash.sessionError": "Не удалось проверить сессию",
    "dash.error": "Произошла ошибка",
    "dash.processing": "Обработка...",
    "dash.processingTime": "Обычно 30-60 секунд",
    "dash.seconds": "секунд",
    "dash.step.analyzing": "Анализ изображения",
    "dash.step.scene": "Создание сцены",
    "dash.step.lighting": "Добавление освещения",
    "dash.step.quality": "Проверка",
    "dash.original": "Оригинал",
    "dash.aiResult": "Результат AI",
    "dash.download": "Скачать",
    "dash.newImage": "Новое изображение",
    "dash.uploadTitle": "Загрузите фото товара",
    "dash.uploadDesc": "Любой формат — до 10МБ",
    "dash.uploadBtn": "Нажмите или перетащите фото",
    "dash.uploadLabel": "Фото товара",
    "dash.modelType": "Тип модели",
    "dash.withoutModel": "📦 Без модели",
    "dash.withoutModelDesc": "Только товар",
    "dash.withModel": "🧑 С моделью",
    "dash.withModelDesc": "С моделью",
    "dash.sceneType": "Тип сцены",
    "dash.studio": "Студия",
    "dash.nature": "Природа",
    "dash.lifestyle": "Лайфстайл",
    "dash.minimalist": "Минимализм",
    "dash.infographic": "Инфографика",
    "dash.imageSize": "Размер: 1080 × 1440 px (3:4)",
    "dash.noCredits": "Кредиты закончились",
    "dash.generateBtn": "Создать изображение (1 кредит)",
    "dash.history": "История",
    "dash.imageReady": "Изображение готово! ✨",
    "dash.onlyImages": "Принимаются только изображения",
    "dash.tooLarge": "Файл слишком большой (макс 10МБ)",
    "dash.networkError": "Ошибка сети. Проверьте подключение к интернету.",
    "dash.authExpired": "Срок аутентификации истёк. Перезапустите приложение.",
    "dash.aiBusy": "AI система занята. Попробуйте через 1-2 минуты.",
    "dash.tgAuthNotFound": "Аутентификация Telegram не найдена. Перезапустите приложение.",
    "dash.sessionExpired": "Сессия истекла. Войдите снова.",
    "dash.uploadError": "Ошибка загрузки изображения",
    "dash.saveError": "Ошибка сохранения данных",
    "dash.aiError": "Ошибка связи с AI сервисом",
    "dash.relogin": "Войдите снова и попробуйте ещё раз",
    "dash.noCreditsBalance": "Кредиты закончились. Пополните баланс",
    "dash.unknownError": "Неизвестная ошибка. Попробуйте снова.",
    "dash.downloading": "Скачивание...",
    "dash.downloaded": "Скачано!",
    "dash.downloadTelegram": "Изображение открыто в браузере. Нажмите и удерживайте для сохранения.",
    "dash.downloadNewTab": "Изображение открыто в новом окне.",
    "dash.downloadError": "Ошибка скачивания",

    // Generate
    "gen.newImage": "Новое изображение",
    "gen.back": "Назад",
    "gen.step.upload": "Загрузка",
    "gen.step.settings": "Настройки",
    "gen.step.result": "Результат",
    "gen.uploadTitle": "Загрузите фото товара",
    "gen.uploadDesc": "JPG, PNG или WEBP — до 5МБ",
    "gen.uploadBtn": "Нажмите или перетащите фото",
    "gen.uploadLabel": "Фото товара",
    "gen.fileTooLarge": "Размер файла должен быть менее 5МБ",
    "gen.continue": "Продолжить",
    "gen.settingsTitle": "Выберите настройки",
    "gen.settingsDesc": "AI создаст изображение на основе выбранных настроек",
    "gen.modelType": "👤 Тип модели",
    "gen.withModel": "С моделью",
    "gen.withModelDesc": "С человеком-моделью",
    "gen.withoutModel": "Без модели",
    "gen.withoutModelDesc": "Только товар",
    "gen.scene": "🎬 Сцена / Фон",
    "gen.nature": "Природа",
    "gen.natureDesc": "На фоне природы",
    "gen.lifestyle": "Лайфстайл",
    "gen.lifestyleDesc": "Жизненная среда",
    "gen.studio": "Студия",
    "gen.studioDesc": "Студийный фон",
    "gen.minimalist": "Минимализм",
    "gen.minimalistDesc": "Просто и чисто",
    "gen.infographic": "Инфографика",
    "gen.infographicDesc": "Информативный дизайн",
    "gen.yourImage": "Ваше изображение",
    "gen.generate": "Создать с AI",
    "gen.sizeInfo": "📐 1080×1440 • ⚡ Готовое изображение",
    "gen.processing": "AI создаёт изображение...",
    "gen.processingDesc": "Создаётся маркетплейс-изображение. Подождите 20-40 сек.",
    "gen.analyzing": "Анализ товара",
    "gen.creatingBg": "фон создаётся",
    "gen.addingModel": "Добавляется модель",
    "gen.proComposition": "Композиция готовится",
    "gen.resizing": "Адаптация к 1080×1440",
    "gen.done": "Готово! 🎉",
    "gen.download": "Скачать",
    "gen.newImageBtn": "Новое изображение",
    "gen.original": "Оригинал",
    "gen.aiResult": "Результат AI",
    "gen.error": "Произошла ошибка. Попробуйте снова.",
    "gen.restart": "Начать заново",
    "gen.success": "Изображение успешно создано!",
    "gen.uploadError": "Ошибка загрузки",
    "gen.downloadError": "Ошибка скачивания",
    "gen.downloaded": "Изображение скачано!",
    "gen.processError": "Ошибка обработки изображения",

    // Balance
    "bal.title": "Баланс",
    "bal.dashboard": "Dashboard",
    "bal.currentBalance": "Текущий баланс",
    "bal.imagesLeft": "изображений осталось",
    "bal.images": "изображений",
    "bal.selectPackage": "Выберите пакет",
    "bal.popular": "Популярный",
    "bal.sum": "сум",
    "bal.perImage": "сум/изобр.",
    "bal.transferTo": "Переведите на карту:",
    "bal.copyCard": "Нажмите для копирования",
    "bal.cardCopied": "Номер карты скопирован",
    "bal.card": "Карта",
    "bal.screenshot": "Скриншот оплаты:",
    "bal.uploadScreenshot": "Загрузите скриншот",
    "bal.submitPayment": "✅ Оплатил",
    "bal.submitting": "Отправка...",
    "bal.submitted": "Заявка отправлена! Ожидайте подтверждения администратора.",
    "bal.adminNote": "После подтверждения администратора кредиты будут начислены на ваш счёт",
    "bal.history": "История оплат",
    "bal.approved": "✅ Одобрено",
    "bal.rejected": "❌ Отклонено",
    "bal.pending": "⏳ Ожидание",
    "bal.loginRequired": "Войдите в систему",
    "bal.error": "Произошла ошибка",

    // Landing - Hero
    "hero.badge": "AI фотографии товаров",
    "hero.title1": "Изображения товаров на",
    "hero.titleHighlight": "новом уровне",
    "hero.title2": "",
    "hero.desc": "Загрузите любое фото товара — AI уберёт фон, настроит освещение и создаст готовое изображение для Uzum, Wildberries, Ozon.",
    "hero.cta": "Начать бесплатно — 1 изображение",
    "hero.howItWorks": "Как работает?",
    "hero.step1": "Загрузка",
    "hero.step1Desc": "Загрузите фото",
    "hero.step2": "Обработка",
    "hero.step2Desc": "AI творит магию",
    "hero.step3": "Скачать",
    "hero.step3Desc": "Получите результат",
    "hero.before": "До",
    "hero.after": "После",
    "hero.showcase1": "Кроссовки",
    "hero.showcase2": "Косметика",
    "hero.showcase3": "Часы",
    "hero.showcaseDesc": "Реальные результаты AI — профессиональные фото для любого товара",

    // Landing - Features
    "feat.label": "Возможности",
    "feat.title": "Все необходимые инструменты",
    "feat.desc": "В вашем браузере. Без оборудования, без фотографа.",
    "feat.bg.title": "Удаление фона",
    "feat.bg.desc": "AI точно вырезает товар — чистые края, готово для любого фона.",
    "feat.light.title": "Освещение",
    "feat.light.desc": "Освещение применяется автоматически — тени, блики и глубина.",
    "feat.detail.title": "Точность деталей",
    "feat.detail.desc": "Усиливает текстуры и мелкие детали, сохраняя естественный вид.",
    "feat.market.title": "Оптимизация для маркетплейсов",
    "feat.market.desc": "Автоматическая подготовка в нужном размере для Uzum, Wildberries, Ozon.",
    "feat.style.title": "5 стилей",
    "feat.style.desc": "От студийного фона до инфографики — выберите нужный стиль.",
    "feat.size.title": "Большой размер",
    "feat.size.desc": "Создание изображений в высоком разрешении.",
    "feat.speed.title": "Быстрая работа",
    "feat.speed.desc": "Результат за секунды. Обработка каталога в пакетном режиме.",

    // Landing - Marketplace
    "market.label": "Готово для маркетплейсов",
    "market.title1": "Оптимизировано для каждого",
    "market.titleHighlight": "маркетплейса",
    "market.title2": "",
    "market.desc": "Выберите платформу — мы автоматически настроим размер, отступы и требования.",

    // Landing - Pricing
    "price.label": "Цены",
    "price.title": "Простые и",
    "price.titleHighlight": "доступные цены",
    "price.desc": "Начните бесплатно. Расширяйте по мере необходимости.",
    "price.free": "Бесплатно",
    "price.freeDesc": "Попробуйте",
    "price.freeFeat1": "1 бесплатное изображение",
    "price.freeFeat2": "Все стили",
    "price.start": "Начать",
    "price.buy": "Купить",
    "price.popular": "Самый популярный",
    "price.onetime": "Разовая проба",
    "price.small": "Маленький пакет",
    "price.medium": "Средний пакет",
    "price.active": "Для активных продавцов",
    "price.big": "Для крупных магазинов",
    "price.business": "Бизнес пакет",
    "price.imageGen": "изображений",
    "price.hd": "HD качество",
    "price.allFormats": "Все форматы",
    "price.viaTelegram": "Через Telegram бот",
    "price.batch": "Пакетная обработка",
    "price.fastSupport": "Быстрая поддержка",
    "price.personalSupport": "Персональная поддержка",
    "price.saving": "экономия",
    "price.hint": "💡 Чем больше покупаете — тем дешевле каждое изображение!",

    // Landing - Roadmap
    "road.label": "Скоро",
    "road.title": "Наши планы",
    "road.desc": "Создаём лучшие инструменты для продавцов маркетплейсов.",
    "road.infographic": "AI Инфографика",
    "road.infographicDesc": "Автоматическое создание инфографики из данных товара.",
    "road.video": "AI Видео",
    "road.videoDesc": "Короткие видео товаров для маркетплейс листингов.",
    "road.model": "Виртуальная модель",
    "road.modelDesc": "AI модели — без фотосессии.",
    "road.analysis": "Анализ конкурентов",
    "road.analysisDesc": "Анализ изображений конкурентов и рекомендации.",
    "road.lang": "Мультиязычность",
    "road.langDesc": "Полная поддержка узбекского, русского и английского.",

    // Landing - CTA
    "cta.title": "Поднимите изображения товаров на новый уровень",
    "cta.desc": "Создавайте изображения вместе с тысячами продавцов маркетплейсов.",
    "cta.btn": "Начать бесплатно — 1 изображение",

    // Footer
    "footer.features": "Возможности",
    "footer.pricing": "Цены",
    "footer.login": "Войти",
  },
};

const LanguageContext = createContext<LanguageContextType>({
  lang: "uz",
  setLang: () => {},
  t: (key) => key,
});

export const LanguageProvider = ({ children }: { children: ReactNode }) => {
  const [lang, setLangState] = useState<Lang>(() => {
    const saved = localStorage.getItem("app-lang");
    return (saved === "ru" || saved === "uz") ? saved : "uz";
  });

  const setLang = (l: Lang) => {
    setLangState(l);
    localStorage.setItem("app-lang", l);
  };

  const t = (key: string) => translations[lang][key] || key;

  return (
    <LanguageContext.Provider value={{ lang, setLang, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => useContext(LanguageContext);
